In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
data=pd.read_csv('c:/Bit_data/FIFA.csv',index_col=0)
data

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,https://cdn.sofifa.org/teams/2/light/121.png,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,https://cdn.sofifa.org/teams/2/light/703.png,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,https://cdn.sofifa.org/teams/2/light/1944.png,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,https://cdn.sofifa.org/teams/2/light/15048.png,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,https://cdn.sofifa.org/teams/2/light/15048.png,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18207 entries, 0 to 18206
Data columns (total 88 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Photo                     18207 non-null  object
 4   Nationality               18207 non-null  object
 5   Flag                      18207 non-null  object
 6   Overall                   18207 non-null  int64
 7   Potential                 18207 non-null  int64
 8   Club                      17966 non-null  object
 9   Club Logo                 18207 non-null  object
 10  Value                     18207 non-null  object
 11  Wage                      18207 non-null  object
 12  Special                   18207 non-null  int64
 13  Preferred Foot            18159 non-null  object
 14  International Reputation  18159 non-null  float64
 15  Weak Foot                 18159 non-null  float64
 16  Skill Moves               18159 non-null  float64
 17  Work Rate                 18159 non-null  object
 18  Body Type                 18159 non-null  object
 19  Real Face                 18159 non-null  object
 20  Position                  18147 non-null  object
 21  Jersey Number             18147 non-null  float64
 22  Joined                    16654 non-null  object
 23  Loaned From               1264 non-null   object
 24  Contract Valid Until      17918 non-null  object
 25  Height                    18159 non-null  object
 26  Weight                    18159 non-null  object
 27  LS                        16122 non-null  object
 28  ST                        16122 non-null  object
 29  RS                        16122 non-null  object
 30  LW                        16122 non-null  object
 31  LF                        16122 non-null  object
 32  CF                        16122 non-null  object
 33  RF                        16122 non-null  object
 34  RW                        16122 non-null  object
 35  LAM                       16122 non-null  object
 36  CAM                       16122 non-null  object
 37  RAM                       16122 non-null  object
 38  LM                        16122 non-null  object
 39  LCM                       16122 non-null  object
 40  CM                        16122 non-null  object
 41  RCM                       16122 non-null  object
 42  RM                        16122 non-null  object
 43  LWB                       16122 non-null  object
 44  LDM                       16122 non-null  object
 45  CDM                       16122 non-null  object
 46  RDM                       16122 non-null  object
 47  RWB                       16122 non-null  object
 48  LB                        16122 non-null  object
 49  LCB                       16122 non-null  object
 50  CB                        16122 non-null  object
 51  RCB                       16122 non-null  object
 52  RB                        16122 non-null  object
 53  Crossing                  18159 non-null  float64
 54  Finishing                 18159 non-null  float64
 55  HeadingAccuracy           18159 non-null  float64
 56  ShortPassing              18159 non-null  float64
 57  Volleys                   18159 non-null  float64
 58  Dribbling                 18159 non-null  float64
 59  Curve                     18159 non-null  float64
 60  FKAccuracy                18159 non-null  float64
 61  LongPassing               18159 non-null  float64
 62  BallControl               18159 non-null  float64
 63  Acceleration              18159 non-null  float64
 64  SprintSpeed               18159 non-null  float64
 65  Agility                   18159 non-null  float64
 66  Reactions                 18159 non-null  float64
 67  Balance                   18159 non-null  float64
 68  ShotPower                 18159 non-null  float64
 69  Jumping                   18159 non-null  float64
 70  Stamina                   18159 non-null  float64
 71  Strength                  18159 non-null  float64
 72  LongShots                 18159 non-null  float64
 73  Aggression                18159 non-null  float64
 74  Interceptions             18159 non-null  float64
 75  Positioning               18159 non-null  float64
 76  Vision                    18159 non-null  float64
 77  Penalties                 18159 non-null  float64
 78  Composure                 18159 non-null  float64
 79  Marking                   18159 non-null  float64
 80  StandingTackle            18159 non-null  float64
 81  SlidingTackle             18159 non-null  float64
 82  GKDiving                  18159 non-null  float64
 83  GKHandling                18159 non-null  float64
 84  GKKicking                 18159 non-null  float64
 85  GKPositioning             18159 non-null  float64
 86  GKReflexes                18159 non-null  float64
 87  Release Clause            16643 non-null  object
dtypes: float64(38), int64(5), object(45)
memory usage: 12.4+ MB

## 1. 사용 안할 열,  행 삭제

In [4]:
data.drop(['ID', 'Photo', 'Flag', 'Club Logo', 'Real Face'], axis=1, inplace=True)
data

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,1471,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,1307,Right,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,1098,Right,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,1189,Right,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,1228,Right,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,1321,Right,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [5]:
# null 값이 너무 많았던 'Laded From' 열 삭제
data.drop(['Loaned From'], axis=1, inplace=True)

## 2. 능력치 정제

In [7]:
data_stats=data.loc[:, 'LS':'RB']

stats=data_stats.columns

for i in range(len(data)):
    if data_stats.loc[i].isnull().sum() != 0:
        continue
    for stat in stats:
        data.loc[i, stat]=eval(data.loc[i, stat])

## 3. 결측 행삭제

In [8]:
# Preferred Foot 부터 Relase Clause까지 데이터 없는 48명 데이터 삭제

In [9]:
data.iloc[13236:13283, :]

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
13236,J. McNulty,33,Scotland,62,62,Rochdale,€120K,€1K,1510,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13237,J. Barrera,29,Nicaragua,62,62,Boyacá Chicó FC,€300K,€1K,1532,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13238,J. Stead,35,England,62,62,Notts County,€140K,€3K,1573,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13239,A. Semprini,20,Italy,62,72,Brescia,€425K,€1K,1610,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13240,R. Bingham,24,England,62,66,Hamilton Academical FC,€400K,€1K,1481,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13241,K. Dankowski,21,Poland,62,72,Śląsk Wrocław,€425K,€1K,1692,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13242,I. Colman,23,Argentina,62,70,Club Atlético Aldosivi,€450K,€2K,1663,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13243,M. Feeney,19,England,62,78,Everton,€600K,€5K,1328,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13244,R. Minor,30,Denmark,62,62,Hobro IK,€230K,€2K,1244,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13245,Klauss,21,Brazil,62,69,HJK Helsinki,€425K,€1K,1549,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13246,I. Sissoko,22,France,62,68,AS Béziers,€425K,€2K,1494,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13247,F. Hart,28,Austria,62,62,SV Mattersburg,€240K,€3K,1630,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13248,L. McCullough,24,Northern Ireland,62,69,Tranmere Rovers,€375K,€2K,1461,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13249,Li Yunqiu,27,China PR,62,62,Shanghai Greenland Shenhua FC,€250K,€3K,1636,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13250,F. Garcia,29,Paraguay,62,62,Itagüí Leones FC,€300K,€1K,1454,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13251,R. Haemhouts,34,Belgium,62,62,NAC Breda,€150K,€2K,1665,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13252,E. Binaku,22,Albania,62,70,Malmö FF,€375K,€1K,1587,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13253,G. Miller,31,Scotland,62,62,Carlisle United,€200K,€2K,1535,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13254,A. Aidonis,17,Germany,62,82,VfB Stuttgart,€550K,€2K,1418,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13255,L. Sowah,25,Germany,62,65,Hamilton Academical FC,€325K,€1K,1693,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13256,R. Deacon,26,England,62,62,Dundee FC,€325K,€1K,1712,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13257,Jang Hyun Soo,25,Korea Republic,62,65,Suwon Samsung Bluewings,€375K,€2K,1536,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13258,A. Al Malki,23,Saudi Arabia,62,67,Al Wehda,€350K,€3K,1664,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13259,E. Guerrero,27,Chile,62,65,CD Palestino,€300K,€1K,1316,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13260,Hernáiz,20,Spain,62,69,Albacete BP,€425K,€1K,1574,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13261,H. Al Mansour,25,Saudi Arabia,62,64,Al Nassr,€300K,€5K,1665,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13262,H. Paul,24,Germany,62,66,TSV 1860 München,€325K,€1K,1625,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13263,S. Bauer,25,Austria,62,66,FC Admira Wacker Mödling,€325K,€2K,1354,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13264,M. Chergui,29,France,62,62,Grenoble Foot 38,€300K,€1K,1620,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13265,D. Gardner,28,England,62,62,Oldham Athletic,€300K,€3K,1740,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13266,L. Bengtsson,20,Sweden,62,73,Hammarby IF,€525K,€1K,1549,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13267,F. Jaramillo,22,Colombia,62,70,Itagüí Leones FC,€450K,€1K,1607,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13268,L. Garguła,37,Poland,62,62,Miedź Legnica,€100K,€1K,1542,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13269,S. Rivera,26,Colombia,62,64,Jaguares de Córdoba,€375K,€1K,1552,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13270,Vinicius,19,Brazil,62,77,Bologna,€525K,€1K,1141,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13271,F. Sepúlveda,26,Chile,62,63,CD Antofagasta,€290K,€1K,1497,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13272,L. Spence,22,Scotland,62,70,Dundee FC,€450K,€1K,1614,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13273,B. Lepistu,25,Estonia,62,67,Kristiansund BK,€400K,€1K,1686,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13274,A. Abruscia,27,Italy,62,62,TSV 1860 München,€325K,€2K,1670,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13275,E. González,23,Venezuela,62,70,Boyacá Chicó FC,€375K,€1K,1542,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13276,M. Al Amri,26,Saudi Arabia,62,63,Al Raed,€290K,€3K,1679,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13277,J. Rebolledo,26,Chile,62,62,Deportes Iquique,€325K,€1K,1675,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13278,C. Mamengi,17,Netherlands,62,79,FC Utrecht,€550K,€1K,1545,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13279,P. Mazzocchi,22,Italy,62,69,Perugia,€350K,€1K,1681,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13280,Y. Ammour,19,France,62,77,Montpellier HSC,€650K,€2K,1478,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13281,Jwa Joon Hyeop,27,Korea Republic,62,62,Gyeongnam FC,€300K,€1K,1729,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13282,O. Marrufo,25,Mexico,62,65,Tiburones Rojos de Veracruz,€375K,€2K,1661,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data = data.dropna(subset=['Preferred Foot'],how='any', axis=0)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18159 entries, 0 to 18206
Data columns (total 82 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      18159 non-null  object
 1   Age                       18159 non-null  int64
 2   Nationality               18159 non-null  object
 3   Overall                   18159 non-null  int64
 4   Potential                 18159 non-null  int64
 5   Club                      17918 non-null  object
 6   Value                     18159 non-null  object
 7   Wage                      18159 non-null  object
 8   Special                   18159 non-null  int64
 9   Preferred Foot            18159 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Weak Foot                 18159 non-null  float64
 12  Skill Moves               18159 non-null  float64
 13  Work Rate                 18159 non-null  object
 14  Body Type                 18159 non-null  object
 15  Position                  18147 non-null  object
 16  Jersey Number             18147 non-null  float64
 17  Joined                    16654 non-null  object
 18  Contract Valid Until      17918 non-null  object
 19  Height                    18159 non-null  object
 20  Weight                    18159 non-null  object
 21  LS                        16122 non-null  object
 22  ST                        16122 non-null  object
 23  RS                        16122 non-null  object
 24  LW                        16122 non-null  object
 25  LF                        16122 non-null  object
 26  CF                        16122 non-null  object
 27  RF                        16122 non-null  object
 28  RW                        16122 non-null  object
 29  LAM                       16122 non-null  object
 30  CAM                       16122 non-null  object
 31  RAM                       16122 non-null  object
 32  LM                        16122 non-null  object
 33  LCM                       16122 non-null  object
 34  CM                        16122 non-null  object
 35  RCM                       16122 non-null  object
 36  RM                        16122 non-null  object
 37  LWB                       16122 non-null  object
 38  LDM                       16122 non-null  object
 39  CDM                       16122 non-null  object
 40  RDM                       16122 non-null  object
 41  RWB                       16122 non-null  object
 42  LB                        16122 non-null  object
 43  LCB                       16122 non-null  object
 44  CB                        16122 non-null  object
 45  RCB                       16122 non-null  object
 46  RB                        16122 non-null  object
 47  Crossing                  18159 non-null  float64
 48  Finishing                 18159 non-null  float64
 49  HeadingAccuracy           18159 non-null  float64
 50  ShortPassing              18159 non-null  float64
 51  Volleys                   18159 non-null  float64
 52  Dribbling                 18159 non-null  float64
 53  Curve                     18159 non-null  float64
 54  FKAccuracy                18159 non-null  float64
 55  LongPassing               18159 non-null  float64
 56  BallControl               18159 non-null  float64
 57  Acceleration              18159 non-null  float64
 58  SprintSpeed               18159 non-null  float64
 59  Agility                   18159 non-null  float64
 60  Reactions                 18159 non-null  float64
 61  Balance                   18159 non-null  float64
 62  ShotPower                 18159 non-null  float64
 63  Jumping                   18159 non-null  float64
 64  Stamina                   18159 non-null  float64
 65  Strength                  18159 non-null  float64
 66  LongShots                 18159 non-null  float64
 67  Aggression                18159 non-null  float64
 68  Interceptions             18159 non-null  float64
 69  Positioning               18159 non-null  float64
 70  Vision                    18159 non-null  float64
 71  Penalties                 18159 non-null  float64
 72  Composure                 18159 non-null  float64
 73  Marking                   18159 non-null  float64
 74  StandingTackle            18159 non-null  float64
 75  SlidingTackle             18159 non-null  float64
 76  GKDiving                  18159 non-null  float64
 77  GKHandling                18159 non-null  float64
 78  GKKicking                 18159 non-null  float64
 79  GKPositioning             18159 non-null  float64
 80  GKReflexes                18159 non-null  float64
 81  Release Clause            16643 non-null  object
dtypes: float64(38), int64(4), object(40)
memory usage: 11.5+ MB

## 4. 단위 환산

In [12]:
# feet to cm
data['Height'] = data['Height'].str.replace('\'', '.')
data['Height'].fillna(0, inplace=True)
data['Height'] = data['Height'].astype(float) * 30.84

In [13]:
data['Height'].round(2)

0        175.79
1        191.21
2        181.96
3        197.38
4        157.59
          ...
18202    181.96
18203    194.29
18204    178.87
18205    157.28
18206    157.28
Name: Height, Length: 18159, dtype: float64

In [14]:
#lbs to kg
data['Weight'] = data['Weight'].str.replace('lbs', '')
data['Weight'].fillna(0, inplace=True)
data['Weight'] = data['Weight'].astype(float) / 2.205

In [15]:
data['Weight'].round(2)

0        72.11
1        82.99
2        68.03
3        76.19
4        69.84
         ...
18202    60.77
18203    77.10
18204    67.12
18205    69.84
18206    79.82
Name: Weight, Length: 18159, dtype: float64

In [16]:
# 돈 단위 통일 ( 유로 -> 달러)

In [17]:
data['Value']

0        €110.5M
1           €77M
2        €118.5M
3           €72M
4          €102M
          ...
18202       €60K
18203       €60K
18204       €60K
18205       €60K
18206       €60K
Name: Value, Length: 18159, dtype: object

In [18]:
def money(col):
    col=col.str.replace('€', '')
    c=col.str.split(pat=(r'([A-Z])'), expand=True)
    c.iloc[:][1].replace('M', 1000000, inplace=True)
    c.iloc[:][1].replace('K', 1000, inplace=True)
    c.fillna(0, inplace=True)
    c[0] = c[0].astype(float)
    c[2] = c[0] * c[1]
    col=c[2]*1.21
    return col.astype(int)

In [19]:
data['Value'] = money(data['Value'])
data['Wage'] = money(data['Wage'])
data['Release Clause'] = money(data['Release Clause'])

## 5. 포지션 grouping

In [20]:
data['Position'].value_counts()

ST     2152
GK     2025
CB     1778
CM     1394
LB     1322
RB     1291
RM     1124
LM     1095
CAM     958
CDM     948
RCB     662
LCB     648
LCM     395
RCM     391
LW      381
RW      370
RDM     248
LDM     243
LS      207
RS      203
RWB      87
LWB      78
CF       74
RAM      21
LAM      21
RF       16
LF       15
Name: Position, dtype: int64

In [21]:
def classify_position(x):
    if x in (['ST','LW','RW','LS','RS','CF','LF','RF']):
        return 'FW'
    elif x in(['CM','RM','LM','CAM','CDM','RCM','LCM','RDM','LDM','RAM','LAM']):
        return 'MD'
    elif x in(['CB','LB','RB','RCB','LCB','RWB','LWB']):
        return 'DF'
    else:
        return 'GK'
    
data['Position simplified'] = data['Position'].apply(classify_position)
data['Position simplified'].value_counts(dropna=False)

MD    6838
DF    5866
FW    3418
GK    2037
Name: Position simplified, dtype: int64

## 6. 시계열 데이터 정제

In [22]:
data['Contract Valid Until']=pd.to_datetime(data['Contract Valid Until'])
data['Contract Valid Until']=data['Contract Valid Until'].dt.to_period(freq='A')
data['Contract Valid Until']

0        2021
1        2022
2        2022
3        2020
4        2023
         ...
18202    2019
18203    2020
18204    2021
18205    2019
18206    2019
Name: Contract Valid Until, Length: 18159, dtype: period[A-DEC]